//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail.Telegram.Bot.BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TelegramBotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelegramBotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Retail.Telegram.Bot.BusinessLogic.TelegramBotMessages", typeof(TelegramBotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cообщите нам информацию о не приобретенном товаре, загрузив фотографию со штрих кодом..
        /// </summary>
        public static string AskPhoto {
            get {
                return ResourceManager.GetString("AskPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, загрузите фотографию, содержащую штрихкод..
        /// </summary>
        public static string AskPhotoError {
            get {
                return ResourceManager.GetString("AskPhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string AskRefusalOption1 {
            get {
                return ResourceManager.GetString("AskRefusalOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        public static string AskRefusalOption2 {
            get {
                return ResourceManager.GetString("AskRefusalOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайн.
        /// </summary>
        public static string AskRefusalOption3 {
            get {
                return ResourceManager.GetString("AskRefusalOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        public static string AskRefusalOption4 {
            get {
                return ResourceManager.GetString("AskRefusalOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удобство.
        /// </summary>
        public static string AskRefusalOption5 {
            get {
                return ResourceManager.GetString("AskRefusalOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбирает.
        /// </summary>
        public static string AskRefusalOption6 {
            get {
                return ResourceManager.GetString("AskRefusalOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string AskRefusalOther {
            get {
                return ResourceManager.GetString("AskRefusalOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, укажите причину отказа.
        /// </summary>
        public static string AskRefusalOtherText {
            get {
                return ResourceManager.GetString("AskRefusalOtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за ваш отзыв..
        /// </summary>
        public static string AskRefusalSuccess {
            get {
                return ResourceManager.GetString("AskRefusalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите вероятную причину отказа покупателя..
        /// </summary>
        public static string AskRefusalText {
            get {
                return ResourceManager.GetString("AskRefusalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о товаре {0} сохранена..
        /// </summary>
        public static string BarCodeText {
            get {
                return ResourceManager.GetString("BarCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я вас не понял. Воспользуйтесь /help для поиска необходимой команды..
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хорошего дня!.
        /// </summary>
        public static string SayGoodBye {
            get {
                return ResourceManager.GetString("SayGoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Вас приветствует Телеграм бот для регистрации отказов покупателей в магазинах Adidas в России.
        ///
        ///Сервис доступен только для сотрудников магазинов. Пожалуйста, введите ваше кодовое слово для доступа..
        /// </summary>
        public static string SayHi {
            get {
                return ResourceManager.GetString("SayHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден. Попробуйте еще раз или обратитесь в службу поддержки..
        /// </summary>
        public static string UserSignInFalse {
            get {
                return ResourceManager.GetString("UserSignInFalse", resourceCulture);
            }
        }
    }
}
